
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml

# Lightwave RF
lightwave:
  host: 192.168.8.163
  switches:
    R2D1:
      name: Landing

# Push Bullet
notify:
  - name: Push Bullet
    platform: pushbullet
    api_key: !secret push_bullet

# Washing Machine
sensor:
  - platform: template
    sensors:
      washing_machine_amps:
        friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Current"
        value_template: '{{ states.switch.smart_plug_washing_machine.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      washing_machine_watts:
        friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Current Consumption"
        value_template: '{{ states.switch.smart_plug_washing_machine.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      washing_machine_total_kwh:
        friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Total Consumption"
        value_template: '{{ states.switch.smart_plug_washing_machine.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washing_machine_volts:
        friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Voltage"
        value_template: '{{ states.switch.smart_plug_washing_machine.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      washing_machine_today_kwh:
        friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Today's Consumption"
        value_template: '{{ states.switch.smart_plug_washing_machine.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
  - platform: template
    sensors:
      washing_machine_status:
        friendly_name: 'Washing Machine Status'
        value_template:  >
          {% if states.sensor.washing_machine_watts.state | float > 3.0 %}
            {{ "Running" }}
          {% elif states.sensor.washing_machine_watts.state | float > 1 %}
            {{ "On" }}
          {% else %}
            {{ "Off" }}
          {% endif %}
      washing_machine_info:
        friendly_name: 'Washing Machine Info'
        entity_id: sensor.time
        value_template:  >
          {%- macro as_formatted_elapsed_time(now, other_date_time) %}
          {% set duration = as_timestamp(now) - as_timestamp(other_date_time) %}
          {% set seconds = (duration % 60) | int %}
          {% set minutes = ((duration / 60) | int) % 60 %}
          {% set hours = (duration / 3600) | int %}
          {{ [hours, "hours", minutes, "minutes", seconds, "seconds"] | join(' ') }}
          {%- endmacro %}
          {% if states.input_text.washing_machine_enriched_status.state == "Running" %}
            Washing machine running for: {{ as_formatted_elapsed_time(now(), states.input_text.washing_machine_enriched_status.last_changed)}}
          {% elif states.input_text.washing_machine_enriched_status.state == "On_After_Running" %}
            Clothes left in the washing machine for: {{ as_formatted_elapsed_time(now(), states.input_text.washing_machine_enriched_status.last_changed)}}
          {% elif states.input_text.washing_machine_enriched_status.state == "On_After_Off" %}
            {{ "Washing machine ready to start" }}
          {% else %}
            {{ "Washing machine is off" }}
          {% endif %}

# Power for Washing Machine
homeassistant:
  customize_glob:
    "*washing_machine*":
      icon: mdi:washing-machine

input_text:
  washing_machine_enriched_status:
    name: 'Washing Machine Enriched Status'
    initial: Off

automation:
  - id: '1556314846684'
    alias: Refresh Washing Machine Info
    initial_state: true
    trigger:
      platform: state
      entity_id: sensor.washing_machine_status
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.washing_machine_enriched_status
          value:  >
            {% if trigger.to_state.state == "Running" %}
              {{ "Running" }}
            {% elif trigger.to_state.state == "On" and trigger.from_state.state == "Running" %}
              {{ "On_After_Running" }}
            {% elif trigger.to_state.state == "On" and trigger.from_state.state == "Off" %}
              {{ "On_After_Off" }}
            {% else %}
              {{ "Off" }}
            {% endif %}
      - service: notify.notify
        data:
          title: >
            {{ "\ud83d\udc55 \ud83d\udc57" }}
          message:  >
            {% if trigger.to_state.state == "Running" %}
              {{ "Washing machine has started" }}
            {% else %}
              {{ "Washing machine has finished" }}
            {% endif %}