sensor:
    - platform: template
      sensors:
        smart_plug_washing_machine_amps:
          friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Current"
          value_template: '{{ states.switch.smart_plug_washing_machine.attributes["current_a"] | float }}'
          unit_of_measurement: 'A'
        smart_plug_washing_machine_watts:
          friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Current Consumption"
          value_template: '{{ states.switch.smart_plug_washing_machine.attributes["current_power_w"] | float }}'
          unit_of_measurement: 'W'
        smart_plug_washing_machine_total_kwh:
          friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Total Consumption"
          value_template: '{{ states.switch.smart_plug_washing_machine.attributes["total_energy_kwh"] | float }}'
          unit_of_measurement: 'kWh'
        smart_plug_washing_machine_volts:
          friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Voltage"
          value_template: '{{ states.switch.smart_plug_washing_machine.attributes["voltage"] | float }}'
          unit_of_measurement: 'V'
        smart_plug_washing_machine_today_kwh:
          friendly_name_template: "{{ states.switch.smart_plug_washing_machine.name}} Today's Consumption"
          value_template: '{{ states.switch.smart_plug_washing_machine.attributes["today_energy_kwh"] | float }}'
          unit_of_measurement: 'kWh'
  